### ISSUE TITLE
Postal

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI_AddOnSkins#102]
Обновленный аддон_скинс не до конца скинит постал.
![WoWScrnShot_082219_224801](https://user-images.githubusercontent.com/19500175/63545215-8bbc0280-c52f-11e9-8bd8-7dfccee0bcd9.jpg)

**Comment by Loaal** [comment]
Already was fixed 2efe98bbffd90b168e51b8f1048166deaf851b73, update AddonSkins
