### ISSUE TITLE
FishingBuddy addon skin problem

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#103]
1x ElvUI-6.01\Modules\Skins\Skins.lua:217: attempt to index local 'frame' (a nil value)
ElvUI_AddOnSkins-1.02\Skins\Addons\fishingBuddy.lua:32: in function <...ddOns\ElvUI_AddOnSkins\Skins\Addons\fishingBuddy.lua:6>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function ?'
CallbackHandler-1.0-6 (Ace3):92: in functionFire'
ElvUI-6.01\Modules\Skins\Skins.lua:684: in function Initialize'
ElvUI-6.01\Modules\Skins\Skins.lua:700: in function <ElvUI\Modules\Skins\Skins.lua:699>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function?'
CallbackHandler-1.0-6 (Ace3):92: in function Fire'
ElvUI-6.01\Core\Core.lua:1047: in functionCallLoadedModule'
ElvUI-6.01\Core\Core.lua:1072: in function InitializeModules'
ElvUI-6.01\Core\Core.lua:1223: in functionInitialize'
ElvUI-6.01\Init.lua:204: in function <ElvUI\Init.lua:203>

  ---
При заходе в игру
скин есть у Елва, но почему то не всегда его подхватывает

**Comment by Loaal** [comment]
Не могу воспроизвести. Убедись что используешь последнюю версию аддона.
https://www.curseforge.com/wow/addons/fishingbuddy/files/442409
