### ISSUE TITLE
Global Cooldown Text on WA

### ISSUE THREAD

**Issue by Merfinx** [ElvUI-WotLK/ElvUI_AddOnSkins#104]
**ru**: заране приношу свои извинения, если это относится скорее к предложениям, чем к багу. Не смог определить. Когда устанавливаешь шрифт на Global в Cooldown Text, после /reload настройки шрифтов КД на WA иконках сбрасываются

Видео с проблемой: https://www.twitch.tv/videos/468949718

**en**: bringing my apologies in advance if it's more as feature request than a bug, haven't decided :/
Global settings in Cooldown Texts for CD of WeakAuras Icons reset after every /reload or initial login. 

Video with problem: https://www.twitch.tv/videos/468949718

**Comment by Loaal** [comment]
ElvUI/ElvUI@320b4b242170c3c93bc7f22cf2e5fbe68226b85b
