### ISSUE TITLE
Skin Request: Factionizer

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#105]
Сделайте пож. скин для небольшого, но очень важного аддона [**Factionizer**](https://www.curseforge.com/wow/addons/factionizer/files/419110)
На данный момент включённый Factionizer с ElvUi выглядит **[так](https://b.radikal.ru/b07/1908/ed/3cf51cadbdd9.jpg)** _(на скрине сам аддон + включены все его опции настройки)_

**Comment by Loaal** [comment]
![image](https://user-images.githubusercontent.com/590348/63778684-f3869a80-c8ed-11e9-9bfc-965679546027.png)
