### ISSUE TITLE
DBM Conflict

### ISSUE THREAD

**Issue by Merfinx** [ElvUI-WotLK/ElvUI_AddOnSkins#106]
До этого использовал бекпортированный DBM-profiles, но специально для видео поставил стандартный DBM, чтобы убедиться, что проблема не в первом.

Вкратце, похоже на то, что АддонСкинс как-то конфликтует с DBM и выдает ошибки при его вызове / появлении баров или попытки настроить Скин через плагин.

Видео с проблемой:
https://www.twitch.tv/videos/473077923

**Comment by Suonu** [comment]
Подтверждаю, после обновления куча ошибок и ДБМ не работает
