### ISSUE TITLE
fishingbuddy новая ошибка

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#108]
Новая ошибка при входе в игру, аддон с https://www.curseforge.com/wow/addons/fishingbuddy/files/442409
```
1x FishingBuddy-0.9.8p1\FishingWatcher.lua:288: attempt to index field '?' (a nil value)
FishingBuddy-0.9.8p1\FishingWatcher.lua:363: in function `WatchUpdate'
FishingBuddy-0.9.8p1\FishingInit.lua:554: in function `Initialize'
FishingBuddy-0.9.8p1\FishingBuddy.lua:1660: in function <FishingBuddy\FishingBuddy.lua:1622>

Locals:
justTime = nil
noshow = true
reset = 1
zone = "Клоака"
subzone = "Черный рынок"
zidx = 26
sidx = 4
FL = <table> {
 GetZoneInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:431:
 tonil = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:135:
 BOBBER_NAME = "Поплавок"
 SCHOOLS = <table> {}
 GetBobberName = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:299:
 GetFishingSkillLine = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:444:
 ChatLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:175:
 IsFishingPool = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:208:
 Translate = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:123:
 SplitFishLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:155:
 watchBobber = true
 WOWVersion = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:18:
 FixupEntry = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:87:
 GetTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:303:
 SkillName = "Рыбная ловля"
 SpellID = 31
 AddTooltip = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:575:
 GetFindFishID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:287:
 SCHOOL_FLOTSAM = 7
 GetLastTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:318:
 SCHOOL_CHURNING = 6
 SCHOOL_OIL = 5
 SetBobberName = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:295:
 GetCurrentSkill = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:412:
 GetFishingSkillInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:395:
 SCHOOL_DEBRIS = 2
 SplitLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:148:
 SCHOOL_WRECKAGE = 1
 SCHOOL_FISH = 0
 IsWorn = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:259:
 IsFishingPole = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:227:
 FindChatWindow = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:589:
 SCHOOL = "school"
 IsMissedFish = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:532:
 GetFishingActionBarID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:498:
 WatchBobber = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:341:
 GetSkillUpInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:481:
 OnFishingBobber = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:326:
 SCHOOL_TASTY = 4
 GetTrackingID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:273:
 SCHOOL_WATER = 3
 GetItemInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:162:
 IsLinkableItem = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:169:
 ExtendDoubleClick = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:363:
 FindSpellID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:370:
 SaveTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:313:
 CheckForDoubleClick = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:346:
 ClearLastTooltipText = <function> de
  ---
```

**Comment by Loaal** [comment]
Код не связан со скином. Без AddonSkins проблема возникает?

**Comment by Vitoshka** [comment]
Пока снова не словил данную ошибку, она бывает очень редко, но бывает и именно при загрузке, буду пробовать без AddonSkins, если что отпишу...

**Comment by Loaal** [comment]
Пробуй перезайти в Клоаке, подзоне Черный рынок. Похожу, что для этой зоны нету информации у аддона.

**Comment by Vitoshka** [comment]
Да, проблема именно в этой зоне, как только достаю удочку и активируется аддон, возникает 3 вида ошибок.
1x FishingBuddy-0.9.8p1\FishingWatcher.lua:288: attempt to index field '?' (a nil value)
FishingBuddy-0.9.8p1\FishingWatcher.lua:363: in function `WatchUpdate'
FishingBuddy-0.9.8p1\FishingWatcher.lua:208: in function `func'
FishingBuddy-0.9.8p1\FishingBuddy.lua:479: in function <FishingBuddy\FishingBuddy.lua:475>
FishingBuddy-0.9.8p1\FishingBuddy.lua:487: in function <FishingBuddy\FishingBuddy.lua:486>

Locals:
justTime = nil
noshow = true
reset = 1
zone = "Клоака"
subzone = "Ведьма и ворон"
zidx = 26
sidx = 2
FL = <table> {
 GetZoneInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:431:
 tonil = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:135:
 BOBBER_NAME = "Поплавок"
 SCHOOLS = <table> {}
 GetBobberName = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:299:
 GetFishingSkillLine = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:444:
 ChatLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:175:
 IsFishingPool = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:208:
 Translate = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:123:
 SplitFishLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:155:
 watchBobber = true
 WOWVersion = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:18:
 FixupEntry = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:87:
 GetTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:303:
 GetFishingActionBarID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:498:
 SkillName = "Рыбная ловля"
 SpellID = 38
 AddTooltip = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:575:
 GetFindFishID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:287:
 SCHOOL_FLOTSAM = 7
 GetLastTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:318:
 SCHOOL_CHURNING = 6
 SCHOOL_OIL = 5
 SetBobberName = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:295:
 GetCurrentSkill = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:412:
 GetFishingSkillInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:395:
 SCHOOL_DEBRIS = 2
 SplitLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:148:
 SCHOOL_WRECKAGE = 1
 SCHOOL_FISH = 0
 IsWorn = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:259:
 IsFishingPole = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:227:
 FindChatWindow = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:589:
 SCHOOL = "school"
 IsMissedFish = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:532:
 lastSkillIndex = 14
 WatchBobber = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:341:
 GetSkillUpInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:481:
 OnFishingBobber = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:326:
 SCHOOL_TASTY = 4
 GetTrackingID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:273:
 SCHOOL_WATER = 3
 GetItemInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:162:
 IsLinkableItem = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:169:
 ExtendDoubleClick = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:363:
 FindSpellID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:370:
 SaveTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:313:
 CheckForDoubleClick = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:346:
 ClearLastToo
  ---
1x FishingBuddy-0.9.8p1\FishingWatcher.lua:288: attempt to index field '?' (a nil value)
FishingBuddy-0.9.8p1\FishingWatcher.lua:363: in function `WatchUpdate'
FishingBuddy-0.9.8p1\FishingWatcher.lua:262: in function `func'
FishingBuddy-0.9.8p1\FishingBuddy.lua:479: in function <FishingBuddy\FishingBuddy.lua:475>
FishingBuddy-0.9.8p1\FishingBuddy.lua:1395: in function <FishingBuddy\FishingBuddy.lua:1374>
FishingBuddy-0.9.8p1\FishingBuddy.lua:1422: in function <FishingBuddy\FishingBuddy.lua:1420>
FishingBuddy-0.9.8p1\FishingBuddy.lua:1633: in function <FishingBuddy\FishingBuddy.lua:1622>

Locals:
justTime = nil
noshow = false
reset = 1
zone = "Клоака"
subzone = "Ведьма и ворон"
zidx = 26
sidx = 2
FL = <table> {
 GetZoneInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:431:
 tonil = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:135:
 BOBBER_NAME = "Поплавок"
 SCHOOLS = <table> {}
 GetBobberName = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:299:
 GetFishingSkillLine = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:444:
 ChatLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:175:
 IsFishingPool = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:208:
 Translate = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:123:
 SplitFishLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:155:
 watchBobber = true
 WOWVersion = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:18:
 FixupEntry = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:87:
 GetTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:303:
 GetFishingActionBarID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:498:
 SkillName = "Рыбная ловля"
 SpellID = 38
 AddTooltip = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:575:
 GetFindFishID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:287:
 SCHOOL_FLOTSAM = 7
 GetLastTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:318:
 SCHOOL_CHURNING = 6
 SCHOOL_OIL = 5
 SetBobberName = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:295:
 GetCurrentSkill = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:412:
 GetFishingSkillInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:395:
 SCHOOL_DEBRIS = 2
 SplitLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:148:
 SCHOOL_WRECKAGE = 1
 SCHOOL_FISH = 0
 IsWorn = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:259:
 IsFishingPole = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:227:
 FindChatWindow = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:589:
 SCHOOL = "school"
 IsMissedFish = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:532:
 lastSkillIndex = 14
 WatchBobber = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:341:
 GetSkillUpInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:481:
 OnFishingBobber = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:326:
 SCHOOL_TASTY = 4
 GetTrackingID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:273:
 SCHOOL_WATER = 3
 GetItemInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:162:
 IsLinkableItem = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:169:
 ExtendDoubleClick = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:363:
 FindSpellID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:370:
 SaveTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:313:
 CheckForDoubleClick = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:346:
 ClearLastTo
  ---
3x FishingBuddy-0.9.8p1\FishingWatcher.lua:288: attempt to index field '?' (a nil value)
FishingBuddy-0.9.8p1\FishingWatcher.lua:363: in function `WatchUpdate'
FishingBuddy-0.9.8p1\FishingWatcher.lua:224: in function `func'
FishingBuddy-0.9.8p1\FishingBuddy.lua:479: in function <FishingBuddy\FishingBuddy.lua:475>
FishingBuddy-0.9.8p1\FishingBuddy.lua:487: in function <FishingBuddy\FishingBuddy.lua:486>

Locals:
justTime = nil
noshow = false
reset = 1
zone = "Клоака"
subzone = "Ведьма и ворон"
zidx = 26
sidx = 2
FL = <table> {
 GetZoneInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:431:
 tonil = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:135:
 BOBBER_NAME = "Поплавок"
 SCHOOLS = <table> {}
 GetBobberName = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:299:
 GetFishingSkillLine = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:444:
 ChatLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:175:
 IsFishingPool = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:208:
 Translate = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:123:
 SplitFishLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:155:
 watchBobber = true
 WOWVersion = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:18:
 FixupEntry = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:87:
 GetTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:303:
 GetFishingActionBarID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:498:
 SkillName = "Рыбная ловля"
 SpellID = 38
 AddTooltip = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:575:
 GetFindFishID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:287:
 SCHOOL_FLOTSAM = 7
 GetLastTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:318:
 SCHOOL_CHURNING = 6
 SCHOOL_OIL = 5
 SetBobberName = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:295:
 GetCurrentSkill = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:412:
 GetFishingSkillInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:395:
 SCHOOL_DEBRIS = 2
 SplitLink = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:148:
 SCHOOL_WRECKAGE = 1
 SCHOOL_FISH = 0
 IsWorn = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:259:
 IsFishingPole = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:227:
 FindChatWindow = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:589:
 SCHOOL = "school"
 IsMissedFish = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:532:
 lastSkillIndex = 14
 WatchBobber = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:341:
 GetSkillUpInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:481:
 OnFishingBobber = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:326:
 SCHOOL_TASTY = 4
 GetTrackingID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:273:
 SCHOOL_WATER = 3
 GetItemInfo = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:162:
 IsLinkableItem = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:169:
 ExtendDoubleClick = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:363:
 FindSpellID = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:370:
 SaveTooltipText = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:313:
 CheckForDoubleClick = <function> @ FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:346:
 ClearLastTo
  ---

**Comment by Loaal** [comment]
Если я правильно понял, ты на сервере с кастомной локацией, вероятно в этом дело.
Ошибка не в скине, чтобы убедится можешь попробовать воспроизвести ошибку с выключенным ElvUI/ElvUI_AddonSkins
