### ISSUE TITLE
atlasLoot error 

### ISSUE THREAD

**Issue by gitnvk** [ElvUI-WotLK/ElvUI_AddOnSkins#111]
ElvUI, v6.01
ElvUIAddOnSkins, v1.03

Opened Atlas and browsed for blacksmith recipes, got an error. Not sure if it affects anything, but here is the log. 

Date: 2019-09-01 01:01:04
ID: 1
Error occured in: Global
Count: 1
Message: ...e\AddOns\ElvUI_AddOnSkins\Skins\Addons\atlasLoot.lua line 14:
   attempt to index field 'db' (a nil value)
Debug:
   [C]: ?
   ...e\AddOns\ElvUI_AddOnSkins\Skins\Addons\atlasLoot.lua:14:
      ...e\AddOns\ElvUI_AddOnSkins\Skins\Addons\atlasLoot.lua:10
   [C]: SetHyperlink()
   AtlasLoot\Core\LootButtons.lua:140: AtlasLootItem_OnEnter()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1
AddOns:
  Swatter, v5.8.4723 (CreepyKangaroo)
  NPCScan, v3.3.5.5
  Altoholic, v3.3.002b
  Atlas, v1.17.0
  AtlasBattlegrounds, v1.17.0
  AtlasDungeonLocs, v1.17.0
  AtlasOutdoorRaids, v1.17.0
  AtlasTransportation, v1.17.0
  AtlasLoot, vv5.11.04
  AtlasLootBurningCrusade, vv5.11.04
  AtlasLootCrafting, vv5.11.04
  AtlasLootOriginalWoW, vv5.11.04
  AtlasLootWorldEvents, vv5.11.04
  AtlasLootWrathoftheLichKing, vv5.11.04
  AtlasLootFu, vv5.11.04
  AucAdvanced, v5.8.4723 (CreepyKangaroo)
  AucFilterBasic, v5.8.4723 (CreepyKangaroo)
  AucFilterOutlier, v5.8.4723.2531
  AucMatchUndercut, v5.8.4723.2531
  AucScanData, v5.8.4723 (CreepyKangaroo)
  AucStatHistogram, v5.8.4723 (CreepyKangaroo)
  AucStatiLevel, v5.8.4723 (CreepyKangaroo)
  AucStatPurchased, v5.8.4723 (CreepyKangaroo)
  AucStatSales, v5.8.4723.2842
  AucStatSimple, v5.8.4723 (CreepyKangaroo)
  AucStatStdDev, v5.8.4723 (CreepyKangaroo)
  AucStatWOWEcon, v5.8.4723.2530
  AucUtilAHWindowControl, v5.8.4723.3311
  AucUtilAppraiser, v5.8.4723.2530
  AucUtilAskPrice, v5.8.4723.3175
  AucUtilAutoMagic, v5.8.4723.3142
  AucUtilCompactUI, v5.8.4723.2530
  AucUtilEasyBuyout, v5.8.4723.3583
  AucUtilFixAH, v5.8.4723 (CreepyKangaroo)
  AucUtilGlypher, v5.8.4723.2545
  AucUtilItemSuggest, v5.8.4723.3108
  AucUtilPriceLevel, v5.8.4723.2545
  AucUtilScanButton, v5.8.4723.2530
  AucUtilScanFinish, v5.8.4723.3576
  AucUtilScanProgress, v5.8.4723.2530
  AucUtilScanStart, v5.8.4723.2530
  AucUtilSearchUI, v5.8.4723.3655
  AucUtilSimpleAuction, v5.8.4723.4546
  AucUtilVendMarkup, v5.8.4723.2530
  BeanCounter, v5.8.4723 (CreepyKangaroo)
  DataStore, v3.3.001
  DataStoreAchievements, v3.3.001
  DataStoreAuctions, v3.3.001
  DataStoreCharacters, v3.3.001
  DataStoreContainers, v3.3.001
  DataStoreCrafts, v3.3.002
  DataStoreCurrencies, v3.3.001
  DataStoreInventory, v3.3.002
  DataStoreMails, v3.3.001
  DataStorePets, v3.3.001
  DataStoreQuests, v3.3.001
  DataStoreReputations, v3.3.001
  DataStoreSkills, v3.3.002
  DataStoreSpells, v3.3.001
  DataStoreStats, v3.3.001
  DataStoreTalents, v3.3.001
  DBMCore, v
  ElvUI, v6.01
  ElvUIAddOnSkins, v1.03
  Enchantrix, v5.8.4723 (CreepyKangaroo)
  EnchantrixBarker, v5.8.4723 (CreepyKangaroo)
  GatherMate, vv.1.25
  GearScoreLite, v3x04
  HealBot, v3.3.5.4
  Informant, v5.8.4723 (CreepyKangaroo)
  MikScrollingBattleText, v5.4.78
  Omen, v3.0.9
  Overachiever, v0.56
  Postal, v3.4.0
  Recount, v
  Routes, vv1.2.8a-4-ga72021e
  Stubby, v5.8.4723 (CreepyKangaroo)
  TradeskillInfo, v1.6.1
  WarmaneAHfix, v1.5
  ZygorGuidesViewer, v2.0
  BlizRuntimeLib_enUS v3.3.5.30300 <logon.warmane.com>
  (ck=a27)

**Comment by Loaal** [comment]
fixed 4c5b3827059f7070994c1979d11aaeab3b9de85d
