### ISSUE TITLE
Ошибка с Recount

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#113]
При заходе в игру возникла данная ошибка
1x ElvUI_AddOnSkins-1.03\Skins\Addons\recount.lua:124: attempt to call global 'SkinFrame' (a nil value)
<in C code>: in function `ShowConfig'
Recount-1127\GUI_Main.lua:582: in function <Recount\GUI_Main.lua:582>

Locals:
(*temporary) = <function> defined =[C]:-1
 = <function> @ Recount\GUI_Config.lua:1502:
 = <function> @ ElvUI_AddOnSkins\Skins\Addons\recount.lua:122:

  ---

**Comment by Loaal** [comment]
Ошибка была исправлена с 8747807f72de390a21ed201f5abfb69a1aab2678
