### ISSUE TITLE
Skin Request: LoseControl

### ISSUE THREAD

**Issue by mrnuggets** [ElvUI-WotLK/ElvUI_AddOnSkins#121]
Shows an icon and duration of the CC spell that is used on you.

https://www.curseforge.com/wow/addons/losecontrol/files/417954

**Comment by Zidras** [comment]
Check this in ElvUI Enhanced: 
![image](https://user-images.githubusercontent.com/10605951/68550638-7a7ee580-03fc-11ea-87d3-f83b1ebb6d84.png)

**Comment by mrnuggets** [comment]
> Check this in ElvUI Enhanced:
> ![image](https://user-images.githubusercontent.com/10605951/68550638-7a7ee580-03fc-11ea-87d3-f83b1ebb6d84.png)

Oh, thank you. I didn't notice it.

I'll close this then.
