### ISSUE TITLE
AdiBags doesn't show Item Quality Border.

### ISSUE THREAD

**Issue by ShadowVariable** [ElvUI-WotLK/ElvUI_AddOnSkins#122]
Adibags skin for ElvUI isn't showing the Item Quality Border even though I have the option enabled. https://i.imgur.com/tkI2zzX.png

**Comment by Loaal** [comment]
It works fine for me, which version are you using?
![image](https://user-images.githubusercontent.com/590348/69009760-b28ca800-0969-11ea-96a1-f9a4e72c8dd0.png)
