### ISSUE TITLE
Details!

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI_AddOnSkins#127]
@Bunny67 Just saw your https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins/commit/14e1492fbb8f3e7388630f264e564c28a0221225 
Could you please share the addon itself? Thank you in advance

PS: I apologize if this isn't the proper way of reaching you for this request

**Comment by Bunny67** [comment]
@Zidras https://github.com/Kowson/Details-Damage-Meter-for-3.3.5a
