### ISSUE TITLE
Request: Quick DKP v2.6.7 - v2.7.5

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI_AddOnSkins#134]
Is it possible to get skin to Quick DKP addon for both versions?
Addon Link: http://trixarian.net/wow/

Thanks in advance.

**Comment by jeyrella** [comment]
+1 here for v2.6.7 would be amazing

**Comment by jeyrella** [comment]
Is there any chance of someone helping out on this one?  I would have a go myself, but I honestly have zero idea where to even start :(

**Comment by Frixen** [comment]
UP, needed

**Comment by Loaal** [comment]
Skin was added #154
