### ISSUE TITLE
Request: add support to Easy frames 3.3.5a

### ISSUE THREAD

**Issue by 3majed** [ElvUI-WotLK/ElvUI_AddOnSkins#138]
For some reason game crash if I enable both elvui + easy frames 3.3.5a even after I disable all unit frames from Elvui options and disable blizzard skins 

here is the addon 
http://www.mediafire.com/file/iuob2t68fghq4vh/EasyFrames_WOTLK.rar/file

**Comment by Loaal** [comment]
EasyFrames contains incorrect versions of libraries, that use features of newer WOW versions.
They should be replaced with versions for WoTLK.
An easy solution would be to remove the line `Libs\CallbackHandler-1.0\CallbackHandler-1.0.xml` from `EasyFrames.toc`
