### ISSUE TITLE
Request: Skin for Elvin Cooldowns

### ISSUE THREAD

**Issue by mrnuggets** [ElvUI-WotLK/ElvUI_AddOnSkins#139]
It would be awesome if you could fine the time to skin Elvin Cooldowns at some point.

This version: https://github.com/bkader/ElvinCDs

Cheers

**Comment by Loaal** [comment]
![elvin](https://user-images.githubusercontent.com/590348/89118784-30b9bc00-d4b1-11ea-9b41-b430cab7944b.jpg)
