### ISSUE TITLE
Skin Request: RCLootCouncil WotLK

### ISSUE THREAD

**Issue by VirtualSmile** [ElvUI-WotLK/ElvUI_AddOnSkins#140]
Hello! I was hoping you could skin for RcLootCouncil WotLK?

It's got the same UI and function as EPGPLootMaster but with a few added features.

Here is the link: https://github.com/ajseward/RcLootCouncil-Wotlk
While in the README it looks like it's already skinned for ElvUI, in-game it looks like standard (non-skinned) version of EPGPLootMaster.

Thank you!

**Comment by Loaal** [comment]
![RCLootCouncil](https://user-images.githubusercontent.com/590348/89118791-4333f580-d4b1-11ea-918e-3869a89d67f3.jpg)
