### ISSUE TITLE
lua error in Auctioneer addon skin

### ISSUE THREAD

**Issue by jeyrella** [ElvUI-WotLK/ElvUI_AddOnSkins#141]
Date: 2020-07-19 11:34:30
ID: 1
Error occured in: Global
Count: 1
Message: ...ns\ElvUI_AddOnSkins\Skins\Addons\auctioneerSuite.lua line 379:
   attempt to call method 'SetTemplate' (a nil value)
Debug:
   [C]: SetTemplate()
   ...ns\ElvUI_AddOnSkins\Skins\Addons\auctioneerSuite.lua:379:
      ...ns\ElvUI_AddOnSkins\Skins\Addons\auctioneerSuite.lua:376
   (tail call): ?
   [C]: ProgressBars()
   Auc-Advanced\CoreScan.lua:812:
      Auc-Advanced\CoreScan.lua:776

**Comment by Loaal** [comment]
Which version of Auctioneer are you using?
#142 is related to this issue and will be closed as duplicate

**Comment by jeyrella** [comment]
You know what, I am so sorry.  Went back and checked and for some reason I'm using TOC 40000 (Version: 5.9.4960)  I have no idea why.
Found one for 30300 and that seems to work correctly.
What a rookie error.  Apologies.
