### ISSUE TITLE
lua error in beancounter addon skin

### ISSUE THREAD

**Issue by jeyrella** [ElvUI-WotLK/ElvUI_AddOnSkins#142]
Date: 2020-07-18 18:51:35
ID: -2
Error occured in: Global
Count: 1
Message: ...AddOns\ElvUI_AddOnSkins\Skins\Addons\beanCounter.lua line 63:
   attempt to index a nil value
Debug:
   (tail call): ?
   (tail call): ?
   [C]: ?
   ...AddOns\ElvUI_AddOnSkins\Skins\Addons\beanCounter.lua:63:
      ...AddOns\ElvUI_AddOnSkins\Skins\Addons\beanCounter.lua:60
   [C]: searchByItemID()
   BeanCounter\BeanCounterSearch.lua:94: startSearch()
   BeanCounter\BeanCounterAPI.lua:108: search()
   BeanCounter\BeanCounter.lua:105:
      BeanCounter\BeanCounter.lua:100
   [C]: pcall()
   Auc-Advanced\CoreUtil.lua:664: SendProcessorMessage()
   Auc-Advanced\CoreScan.lua:1238:
      Auc-Advanced\CoreScan.lua:1236
   (tail call): ?
   [C]: QueryAuctionItems()
   ...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:535:
      ...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:516
   ...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:552: AuctionFrameBrowse_Search()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1

**Comment by Loaal** [comment]
#141
