### ISSUE TITLE
Issue: WeakAuras

### ISSUE THREAD

**Issue by foxtoopia12** [ElvUI-WotLK/ElvUI_AddOnSkins#146]
The latest AddOnSkins for WeakAuras is broken. The setting doesn't exist and the cooldown of the WAs can't be shown.
https://imgur.com/a/HkvPOYw

**Comment by rokpusnik** [comment]
https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins/commit/4c19fab64394e56ab66d43d117380bfdc0d13222

removed since new WA has its own skinning settings

**Comment by Bunny67** [comment]
skin disabled for new backport WA
