### ISSUE TITLE
if i'm not a leader,it will get a error

### ISSUE THREAD

**Issue by coolaken** [ElvUI-WotLK/ElvUI_AddOnSkins#147]
Message: ...erface\AddOns\ElvUI_AddOnSkins\Skins\Addons\oRA3.lua:120: attempt to index global 'oRA3ReadyCheck' (a nil value)
Time: 08/12/20 13:42:12
Count: 1
Stack: (tail call): ?
[C]: ?
...erface\AddOns\ElvUI_AddOnSkins\Skins\Addons\oRA3.lua:120: in function <...erface\AddOns\ElvUI_AddOnSkins\Skins\Addons\oRA3.lua:117>
(tail call): ?
[C]: in function `?'
...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: (*temporary) = "READY_CHECK"
(*temporary) = "毒毒的咕咕"
(*temporary) = 30
(*temporary) = "READY_CHECK"
(*temporary) = "毒毒的咕咕"
(*temporary) = 30
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1

**Comment by coolaken** [comment]
Message: ...erface\AddOns\ElvUI_AddOnSkins\Skins\Addons\oRA3.lua:120: attempt to index global 'oRA3ReadyCheck' (a nil value)
Time: 08/12/20 14:25:49
Count: 1
Stack: (tail call): ?
[C]: ?
...erface\AddOns\ElvUI_AddOnSkins\Skins\Addons\oRA3.lua:120: in function <...erface\AddOns\ElvUI_AddOnSkins\Skins\Addons\oRA3.lua:117>
(tail call): ?
[C]: in function `?'
...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:

**Comment by ArsumPB** [comment]
Message: ...erface\AddOns\ElvUI_AddOnSkins\Skins\Addons\oRA3.lua:120: attempt to index global 'oRA3ReadyCheck' (a nil value)
Time: 08/13/20 20:48:51
Count: 1
Stack: [C]: ?
...erface\AddOns\ElvUI_AddOnSkins\Skins\Addons\oRA3.lua:120: in function <...erface\AddOns\ElvUI_AddOnSkins\Skins\Addons\oRA3.lua:117>
(tail call): ?
[C]: in function `?'
...igs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...igs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...igs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:

**Comment by Zidras** [comment]
Same here
