### ISSUE TITLE
Conflict between AddonSkins and backported retail DBM

### ISSUE THREAD

**Issue by DimitrisLK** [ElvUI-WotLK/ElvUI_AddOnSkins#165]
Just got [this error ](https://pastebin.com/ic5gu53G) after installing the DBM from [here](https://github.com/Zidras/DBM-Icecrown). 

Error happened after I clicked on the minimap icon. I assume it's a problem specific to this version of DBM since I had no problem with the previous one I was using.

**Comment by Zidras** [comment]
To reproduce, it's only to click minimap icon? Nothing else? 
Could you check on a fresh toon/profile? I never have encountered such an error

**Comment by Zidras** [comment]
You should update ElvUI to latest master version (not release). 
HandleCollapseExpandButton is a new skinning function
