### ISSUE TITLE
Lua error with DBM

### ISSUE THREAD

**Issue by Artharok** [ElvUI-WotLK/ElvUI_AddOnSkins#184]
lua error with DBM, when I change talents and then choose my dbm DPS/Heal profile, I get an error: dbm.lua:164: attempt to perform arithmetic on field 'dbm icon size' (a nil value)
![WoWScrnShot_062823_221416](https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins/assets/130411996/d0687aa4-e392-49a1-b180-d2ce6aeb5d95)

**Comment by Zidras** [comment]
Opened as per my request, for me to look over when I have the chance
