### ISSUE TITLE
Spy - Buttons Skin

### ISSUE THREAD

**Issue by Lexblack** [ElvUI-WotLK/ElvUI_AddOnSkins#19]
The buttons are not skinned
![adasd](https://cloud.githubusercontent.com/assets/16202997/14428689/c2df6676-0002-11e6-8022-4a3acca7a93a.png)

**Comment by crumdidlyumshis** [comment]
At one time I had those skinned and I planned on pushing the code, however, I think something happened on my computer before and I lost what I did. Never got around to redoing it. But yes, these need to be skinned. Also the status bar texture.

**Comment by crumdidlyumshis** [comment]
Close, I added this a couple weeks ago.
