### ISSUE TITLE
Merge Plugins/Backport

### ISSUE THREAD

**Issue by lbjdaking23** [ElvUI-WotLK/ElvUI_AddOnSkins#3]
Hi, I noticed this addon you are working on. I personally backported the original AddOnSkins and got it up and working for the most. I was wondering if you would like to take this addon (https://github.com/lbjdaking23/AddOnSkins) and we could make a really good version together. The reason I like this version more than yours is because it keeps the original code that most people know so it would be easier to make/backport addons.

**Comment by Bunny67** [comment]
I gave up the original version as it can work without ElvUI, and my task was to move the skins in another addon.

Ru: Я отказался от оригинальной версии так как она может работать и без ElvUI, а моя задача была переместить скины в другой аддон.

**Comment by lbjdaking23** [comment]
Alright. I just backported it because I was having multiple issues with it loading. Probably because you were still working on it

**Comment by Bunny67** [comment]
There are problems, but better.

Ru: Есть проблемы, но уже лучше.

**Comment by lbjdaking23** [comment]
Awesome. I am willing to help if you need or want it! :)

**Comment by Bunny67** [comment]
The main problem I have is laziness and lack of time, well, I will not refuse help from

Ru: Основная пролема у меня это лень и нехватка времяни, ну и от помощи не откажусь

**Comment by crumdidlyumshis** [comment]
I will be happy to help as well! I did CallToArms last night as my first attempt. I feel now, that I have a grasp on the way the skins are handled, this will teach me how to skin more addons. :) I plan to make a skin for Zygro Leveling Guide

**Comment by crumdidlyumshis** [comment]
Maybe close?
