### ISSUE TITLE
Skada/Recount/Omen - Toggle - Glitches

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI_AddOnSkins#34]
https://youtu.be/KrJzKgESRFM

Button needs to be saved in last selected state. Disabled/Active

**Comment by Bunny67** [comment]
Unfortunately tomorrow fix :(

**Comment by Bunny67** [comment]
check

**Comment by crumdidlyumshis** [comment]
But can the toggle be saved?

https://youtu.be/QUmyPV9umAE

**Comment by Bunny67** [comment]
check

**Comment by crumdidlyumshis** [comment]
Thank you!
