### ISSUE TITLE
BindPad a couple of tweaks needed

### ISSUE THREAD

**Issue by datbunneh** [ElvUI-WotLK/ElvUI_AddOnSkins#37]
@Bunny67 Thanks for adding support for this addon and so fast.
I couple of tweaks are still needed though:
* Spellbook and two more buttons left unskinned
* Spellbinding interface left unskinned

![bindpad_skin2](https://cloud.githubusercontent.com/assets/9550798/18412481/1e8766c4-7798-11e6-9591-8c9304d106b3.png)

**Comment by Bunny67** [comment]
added

**Comment by datbunneh** [comment]
@Bunny67 Thanks, looks awesome!
