### ISSUE TITLE
Find Group

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI_AddOnSkins#41]
Скажи, можно ли оформитьскин для Find Group? Или там какие-то нюансы свои есть? Я читал, что в последней версии код зашифрован. Признаться, нихера не секу в этом. 
Еще было бы очень круто. если бы его можно было встроить в окно чата =) Как рекаунт или скаду.

Find Group здесь есть: https://github.com/maglink/addons/tree/master/FindGroup

**Comment by Bunny67** [comment]
Если имена фреймов есть то скин можно сделать, в окно чата уже будет сложнее.
Как время будет гляну

**Comment by Bunny67** [comment]
Поставил 3-ю версию аддона, это пздц. С ним играть вообще не возможно
![wowscrnshot_092216_193952](https://cloud.githubusercontent.com/assets/5816685/18757405/7ddaef66-80fc-11e6-8de3-e77d75b97500.jpg)
Да и скинить там практически нечего, там все элементы маленькие, через bacdrop будут еще меньше

**Comment by freesay** [comment]
Да, чет я сам её воткнул, труба, фризит. Думаю, нахер вообще этот аддон. Жаль нет альтернатив =(

**Comment by Bunny67** [comment]
Есть, но англ версии

**Comment by freesay** [comment]
То есть? Не работает с русским клиентом? Или не сканирует русский чат? Могу перевести, если расскажешь каким образом это делается.

**Comment by Bunny67** [comment]
Я не помню название, но что то подобное видел. Вечером мб найду

**Comment by freesay** [comment]
Окей, круто, буду ждать.

**Comment by Bunny67** [comment]
https://wow.curseforge.com/addons/lfgshout/files/ нашел такое, но это не то что раньше видел :(

**Comment by freesay** [comment]
Да уж... Это точно не совсем то, что нужно. Но спасибо. Если разыщу что-нибудь дельное, приду сюда с просьбами заскинить =)
