### ISSUE TITLE
Skin Request - Ackis Recipe List

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI_AddOnSkins#44]
Possible to get a skin for this addon?
Here is the latest version for 3.3.5 https://www.wowace.com/projects/arl/files/447314

**Comment by Kamui2040** [comment]
Would love to see this too.
Thank you

**Comment by Loaal** [comment]
Carbonit complex addon, don't think anyone would create skin for it; probably easier way of skinning is editing code directly inside of it.
Anyway you can create separate issue directed for Carbonit .
