### ISSUE TITLE
Recount

### ISSUE THREAD

**Issue by freesay** [ElvUI-WotLK/ElvUI_AddOnSkins#45]
Здравствуй! 
В очередной раз хочу докучать тебе всякой ерундовиной =) 
Скажи, возможно ли как-нибудь "скиннингом" убрать полосу прокрутки в рекаунте? Или это нужно лопатить сам аддон? Когда рекаунт единственный аддон встроенный в чат - ничего страшного. Но когда в окно встроено два аддона - смотрится не очень эстетично.  Вот так это выглядит со включенной полосой прокрутки:
![1](https://cloud.githubusercontent.com/assets/19500175/20699043/33a64266-b616-11e6-8858-a7fabe09a88d.jpg)

А если выключить полосу прокрутки в настройках самого рекаунта, то получится вообще белиберда какая-то:
![2](https://cloud.githubusercontent.com/assets/19500175/20699120/af9973c0-b616-11e6-83a8-6cf75d86425a.jpg)

Полоса остается все равно, просто выезжает за рамки окна аддона. Соответственно, если вытащить окно рекаунта из чата в любую другую область, то вот эта невнятная грыжа так и будет кататься за аддоном =) 
______________________________________________________________________
И еще одна просьба, раз уж дело касается скина рекаунта, погляди пожалуйста, можно ли добавить расстояние буквально в один пиксель между полосами дпс'а и рамкой самого аддона. Как это сделано в омене. Если ты обратишь внимание на первые два скриншота выше, то заметишь, что полосы значений омена висят немного ниже, в сравнении с рекаунтом. Чтоб было понятней о чем речь, я вот увеличил пару кусков с первого скрина:
![default](https://cloud.githubusercontent.com/assets/19500175/20699510/bcde648a-b618-11e6-942f-e03ab92342fb.png)
Немного ясности:
![4](https://cloud.githubusercontent.com/assets/19500175/20699824/732e8b9c-b61a-11e6-9980-1ecf6dbce673.png)
Или, если будет проще, то можно сделать наоборот - убрать это расстояние в скине омена.
P.s.
Это совсем не обязательно, просто мой внутренний перфекционист негодуэ =)) Но если много труда не составит - было бы просто превосходно.

**Comment by Bunny67** [comment]
Скролл бар в рекаунте скрыл. По поводу омена, положение полос изменяется в настройках омена "Врезка полос" в Опциях фона.
