### ISSUE TITLE
wow can't see the addon

### ISSUE THREAD

**Issue by Nividan** [ElvUI-WotLK/ElvUI_AddOnSkins#49]
Hello
I download the addon and put it in the addons folder but in game i can't see it on the addon list.
I got elvui 5.28

**Comment by Apollyonn** [comment]
If your extracted folder looks like this "ElvUI_AddOnSkins-master" then you have to rename it to "ElvUI_AddOnSkins"

**Comment by crumdidlyumshis** [comment]
Yeah this should actually be corrected sometime @Bunny67

:)
