### ISSUE TITLE
Skin Request - Advanced Trade Skill Window

### ISSUE THREAD

**Issue by Kamui2040** [ElvUI-WotLK/ElvUI_AddOnSkins#56]
I would like to request the above addon to be skinned if possible, because it is a wide spread addon.
Thank you

**Comment by Loaal** [comment]
WIP
![capture](https://cloud.githubusercontent.com/assets/590348/23471971/502345bc-febc-11e6-9458-61a1f5692b98.PNG)

**Comment by Bunny67** [comment]
:D

**Comment by Kamui2040** [comment]
DAMN!
You fast bro :D
Thank you!

**Comment by Kamui2040** [comment]
@Loaal Just noticed that this button is unskinned, happens when you have something on your queue that requires ingredients that can be bought from an npc. The Buy reagents button.
![wowscrnshot_033117_133656](https://cloud.githubusercontent.com/assets/11214249/24548986/9a69f676-1617-11e7-9eb1-c1d99d246d71.jpg)
