### ISSUE TITLE
Skin Request: Enchantrix

### ISSUE THREAD

**Issue by Kamui2040** [ElvUI-WotLK/ElvUI_AddOnSkins#60]
So it's me again requesting yet another skin:
This time I would like to request Enchantrix which is part of the Auctioneer suite, or if it's all the same to you the Auctioneer addon.
At the moment this is what it looks like:
![wowscrnshot_030717_193511](https://cloud.githubusercontent.com/assets/11214249/23672034/a85b89d2-036d-11e7-8c7a-7dc1559a9a38.jpg)

**Comment by Kamui2040** [comment]
Thanks for the quick skinning, but a small part is missing. The window that pops up asking you if you want to disenchant/mill/prospect stuff.
![wowscrnshot_032817_120844](https://cloud.githubusercontent.com/assets/11214249/24400312/448ce916-13b0-11e7-99f6-fc076525c912.jpg)
If you could look into it when you got the time I'd be very grateful.
Thank you for all the hard work.

**Comment by Loaal** [comment]
Check updated version. Probably problem with addon load order.

**Comment by Kamui2040** [comment]
Fixed it thank you.
