### ISSUE TITLE
Recount/ Skada dissapered  after embed

### ISSUE THREAD

**Issue by Olesong** [ElvUI-WotLK/ElvUI_AddOnSkins#71]
[http://imgur.com/a/WgPCQ](url)
I am using elvui + addon skins for 4 months and never have problem like this. But today i log in and saw that recount and skada have dissapared in my right chat panel. They was embedded. On other toons everything is fine only 1 have problem like this.

**Comment by namaless** [comment]
I have the same problem too. I still working to fix it.

**Comment by namaless** [comment]
@Olesong I found a trick for temp fix:
- In addonskin options panel select "Embed Below Top Tab"
- Click on the chat tab and the dps meter appear
- Then deselect the option and working fine

I need time to understand what happen but for now working fine.

**Comment by Bunny67** [comment]
fixed in 7412ea68caa45ee41d8f26d06e163ea2355ecd08
