### ISSUE TITLE
Problem with displaying text in the Recount addon

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#76]
http://i062.radikal.ru/1711/17/7cc1ca8c3493.jpg

Problem with displaying the panel in the **Recount** addon (**the addon itself works fine)**
Each time I enter the game, the top panel is moved to the left and closes the text display.

**Comment by Bunny67** [comment]
Check

**Comment by Vitoshka** [comment]
Проблема не решилась
http://i075.radikal.ru/1711/ac/090c60ae9f2c.jpg
изображение смещается влево, как только входишь в игру

**Comment by Vitoshka** [comment]
Всё корректно работает, спасибо, надеюсь, и наверное не только один я, что вы также добавите в поддержу скина в ElvUI_AddOnSkins для популярного аддона WIM (WoW Instant Messenger)

https://www.wowace.com/projects/wim-3/files?filter-game-version=2020709689%3A98

**Comment by Vitoshka** [comment]
После последнего обновления текст сместился от центра вниз и стал залазить на границы окантовки
http://s11.radikal.ru/i183/1711/0c/374c93ebffb5.jpg

**Comment by Bunny67** [comment]
Это было всегда, как исправить я пока что не знаю

**Comment by Vitoshka** [comment]
что интересно, в **предпоследнем** патче для ElvUI_AddOnSkins такой проблемы не было
