### ISSUE TITLE
The problem with the transparency display of the Omen addon/Проблема с отображением прозрачности Omen.

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#83]
Проблема с отображением прозрачности Omen.
На аддон Omen, некорректно действует прозрачность если включён скин ElvUi для Omen!
[Пример 1](https://d.radikal.ru/d21/1805/18/6ad413d289f7.jpg) (Скин ElvUi включен для аддона  Omen).
[Пример 2](https://c.radikal.ru/c27/1805/30/dc2b439219a1.jpg ) (Скин ElvUi **выключен** для аддона  Omen).
Пробовал изменить прозрачность самого Omen в настройках данного аддона при включённом скине ElvUi, что повлекло за собой изменение прозрачности заголовка и отличие от Scada по отображению. [Пример изменения. ](https://a.radikal.ru/a08/1805/2d/99471aa7a0ae.jpg)
***На досуге снова ещё раз просматривал настройки ElvUi и заметил, [похожую функцию](https://d.radikal.ru/d42/1805/79/599d9d90a885.jpg) с различными вариантами но только для Scada, может решением проблемы будет добавить похожие функции для Omen, а также и для Recount, так как они отсутствуют на данный момент и это я уверен решит нюансы неправильной прозрачности.**

**The problem with the Omen transparency.
On the addon Omen, the transparency is not working correctly if the ElvUi skin for Omen is included!
[Example 1](https://d.radikal.ru/d21/1805/18/6ad413d289f7.jpg) (Skin ElvUi is included for Omen addon).
[Example 2](https://c.radikal.ru/c27/1805/30/dc2b439219a1.jpg) (Skin ElvUi ** is off ** for Omen addon).
I tried to change the transparency of Omen itself in the settings of this add-on when the ElvUi skin was turned on, which caused a change in the transparency of the header and a difference from Scada on the display. [Example of change.](https://a.radikal.ru/a08/1805/2d/99471aa7a0ae.jpg)
*** At leisure, I again looked through the ElvUi settings and noticed [a similar function](https://d.radikal.ru/d42/1805/79/599d9d90a885.jpg) with different options but only for Scada, can solve the problem will add similar functions for Omen, as well as for Recount, since they are not available at the moment and I'm sure it will solve the nuances of incorrect transparency. ****

**Comment by Loaal** [comment]
Skin replace default backdrop with styled one.
Works as intended.
Few backdrop styles was added into AddonSkins option menu (same options as Skada)
fe5cef10ce3c306014681b83240ca4ba22ff3666
