### ISSUE TITLE
Error ElvUI AddOnSkins - WIM

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#87]
**When I enter the game periodically this error occurs**
Когда я захожу в игру периодически возникает данная ошибка

1x ElvUI_AddOnSkins-1.02\Skins\Addons\WIM.lua:289: attempt to index field 'db' (a nil value)
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6:92: in function `Fire'
ElvUI-5.41\modules\skins\skins.lua:607: in function `Initialize'
ElvUI-5.41\modules\skins\skins.lua:641: in function <ElvUI\modules\skins\skins.lua:640>
CallbackHandler-1.0-6:157: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6:92: in function `Fire'
ElvUI-5.41\core\core.lua:1102: in function `InitializeModules'
ElvUI-5.41\core\core.lua:1239: in function `Initialize'
ElvUI-5.41\init.lua:132: in function <ElvUI\init.lua:131>

  ---

**Comment by Loaal** [comment]
fixed 29e376e2797acce0ca69e3d1b0be9eb760632e66
