### ISSUE TITLE
Problem with addon Pallypower and ElvUI AddOnSkins

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#88]
**When I have the addon ElvUI AddOnSkins (pallypower) turned on, the size settings for the main buff window and the timer window do not work. And also the choice of a different background of the timer window does not work.**

Когда у меня включен скина аддона ElvUI AddOnSkins (pallypower), то не работают настройки размера главного окна баффов и окна таймеров. И также не работает выбор различного фона окна таймеров.

**Examples:** Skin ElvUI AddOnSkins (pallypower) **ON**
https://a.radikal.ru/a02/1806/7a/dd20eae1e2ad.jpg
https://a.radikal.ru/a43/1806/c5/d7b4e1d0d335.jpg
https://b.radikal.ru/b41/1806/37/81c82851d838.jpg

**Examples:** Skin ElvUI AddOnSkins (pallypower) **OFF**
https://a.radikal.ru/a03/1806/7d/a8095a3b1bcc.jpg
https://a.radikal.ru/a40/1806/64/1ebed4ef1804.jpg
https://d.radikal.ru/d14/1806/e9/91b0f5170f79.jpg

**Comment by Loaal** [comment]
#97
