### ISSUE TITLE
Skin Request: Retri/Prot FCFS helper (CLCRet) + editing of incorrect work with ElvUI

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#89]
**Please make a skin for the add-on of [CLCRet](https://wow.curseforge.com/projects/clcret/files/439502), also need an important correct work of the addon and the option shown in the [screenshot](https://d.radikal.ru/d29/1806/5f/8cf6aa763023.jpg). Now the selection of the display option does not work, the icons are always displayed, and the icons are displayed immediately when the character is loaded into the game.
Checked also when I had only four add-ons included (ElvUI, ElvUI_Config, CLCRet and CLCRet_Options).
The compatibility problem is in ElvUI (or I need to disable a certain option in the addon settings).
When ElvUI is turned off everything works correctly. And the display disappears when I do not have a dedicated target.**

Сделайте пожалуйста скин для аддона [CLCRet](https://wow.curseforge.com/projects/clcret/files/439502), также нужна важно-корректная работа аддона и опцией которая показана на [скриншоте](https://d.radikal.ru/d29/1806/5f/8cf6aa763023.jpg). Сейчас выбор опции отображения не работает, иконки показываются всегда, также иконки отображаются сразу при загрузке персонажа в игру. 
Проверил также когда у меня было включено только четыре аддона (ElvUI, ElvUI_Config, CLCRet и CLCRet_Options). 
Проблема совместимости именно в ElvUI (или же мне нужно отключить определённую опцию в настройках аддона ElvUI). 
Когда ElvUI выключен всё корректно работает. И отображение пропадает когда у меня нет выделенной цели.

**Comment by Vitoshka** [comment]
Проблема до сих пор актуальна

**Comment by Loaal** [comment]
Добавил скин.
Проблему со скрытием без цели не могу воспроизвести. Использовал версию [1.3.03.025](https://www.curseforge.com/wow/addons/clcret/files/439502)

**Comment by Vitoshka** [comment]
https://a.radikal.ru/a28/1908/28/e03bbbbc2aaf.jpg
Как видно цель **не** выбрана, а ротация показывается, в аддоне вкладка - текущая цель выставлена..., у меня подозрение что какае-то библиотека в елве запускает отображение автоматически...

**Comment by Vitoshka** [comment]
Повторюсь ещё раз:
Проверил также когда у меня было включено только четыре аддона (ElvUI, ElvUI_Config, CLCRet и CLCRet_Options).
Проблема совместимости именно в ElvUI (или же мне нужно отключить определённую опцию в настройках аддона ElvUI).
Когда ElvUI выключен всё корректно работает. И отображение пропадает когда у меня нет выделенной цели.

**Comment by Vitoshka** [comment]
С версией 1.3.03.025 та же проблема, проверил только что

**Comment by Vitoshka** [comment]
После сегодняшнего обновления проблема не решилась, пробовал только 4 аддона:
1) ElvUI
2) ElvUI_OptionsUI
3) CLCRet
4) CLCRet_Options
Если отключаю 1-2, то всё нормально отображается, как я писал выше...

**Comment by Loaal** [comment]
Нашел проблему. В кратце, это баг аддона, который всплывает изза большего номера версии одной из либ в ElvUI.
Добавил фикс в ElvUI_Enhanced ElvUI-WotLK/ElvUI_Enhanced@d77084667d56cb1f026aec1dfb2aa056f529bc3e
