### ISSUE TITLE
Skin Request: TrinketMenu/Поддержка скина аддона TrinketMenu

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#91]
Is it possible to make [TrinketMenu](https://wow.curseforge.com/projects/trinket-menu/files?filter-game-version=2020709689%3A43) compatible with ElvUI.
Thanks.

https://a.radikal.ru/a24/1806/ab/f96e18b518ad.jpg

**Comment by robgha01** [comment]
Yes i have added support for it in https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins/pull/93
