### ISSUE TITLE
Problem with addon SexyCooldown and ElvUI AddOnSkins

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#92]
**When I have the addon ElvUI AddOnSkins (SexyCooldown) turned **on**. [These addon functions](https://a.radikal.ru/a13/1806/83/027ffeb01fad.jpg) do not work. _Especially the border and background transparency functions do not work._**

Когда у меня включён аддон ElvUI AddOnSkins (SexyCooldown). [Эти функции не работают](https://a.radikal.ru/a13/1806/83/027ffeb01fad.jpg). _Особенно не работают функции прозрачности границы бара и фона бара._

**Comment by Loaal** [comment]
Skin replace default backdrop with styled one.
Works as intended.
