### ISSUE TITLE
Wim ElvUI_AddOnSkins error

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#98]
**When I enter the game this error occurs**

1x ElvUI_AddOnSkins-1.02\Skins\Addons\WIM.lua:289: attempt to index field 'db' (a nil value)
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6:92: in function `Fire'
ElvUI-5.45\modules\skins\skins.lua:607: in function `Initialize'
ElvUI-5.45\modules\skins\skins.lua:641: in function <ElvUI\modules\skins\skins.lua:640>
CallbackHandler-1.0-6:157: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6:92: in function `Fire'
ElvUI-5.45\core\core.lua:1103: in function `InitializeModules'
ElvUI-5.45\core\core.lua:1246: in function `Initialize'
ElvUI-5.45\init.lua:128: in function <ElvUI\init.lua:127>

  ---

**Comment by Loaal** [comment]
#87
