### ISSUE TITLE
Skin Request - Altoholic

### ISSUE THREAD

**Issue by Altherius** [ElvUI-WotLK/ElvUI_AddOnSkins#99]
Good evening.

I would like to request a skin for the AddonSkins ElvUI plugin for the Altoholic add-on in its version 3.3.002b. FYI this add-on is currently supported by TukUI/ElvUI so you can go ahead and look what its looks like. The 3.3.002b version's design being fundamentally the same.

**Comment by Loaal** [comment]
ae3c8a90875dae9db5752fb97d1aaf53963d59b8
